# -*- coding: UTF-8 -*-

import os


def _model_list(name, fallback=None):
	value = os.getenv(name, fallback or "")
	return [item.strip() for item in value.split(",") if item.strip()]

# Primary provider: Google Gemini. OpenRouter acts as the fallback provider.
GEMINI_BASE_URL = os.getenv(
	"GEMINI_BASE_URL",
	"https://generativelanguage.googleapis.com/v1beta/openai/",
)
GEMINI_MODEL_ID = os.getenv("GEMINI_MODEL_ID")
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")
GEMINI_ASR_MODELS = _model_list("GEMINI_ASR_MODELS", GEMINI_MODEL_ID)
GEMINI_VIDEO_MODELS = _model_list("GEMINI_VIDEO_MODELS", GEMINI_MODEL_ID)
GEMINI_TEXT_MODELS = _model_list("GEMINI_TEXT_MODELS", GEMINI_MODEL_ID)
OPENROUTER_BASE_URL = os.getenv(
	"OPENROUTER_BASE_URL",
	"https://openrouter.ai/api/v1",
)
OPENROUTER_MODEL_ID = os.getenv("OPENROUTER_MODEL_ID")
OPENROUTER_ASR_MODEL_ID = os.getenv("OPENROUTER_ASR_MODEL_ID")
OPENROUTER_API_KEY = os.getenv("OPENROUTER_API_KEY")
OPENROUTER_TEXT_MODELS = _model_list("OPENROUTER_TEXT_MODELS", OPENROUTER_MODEL_ID)
OPENROUTER_ASR_MODELS = _model_list("OPENROUTER_ASR_MODELS", OPENROUTER_ASR_MODEL_ID)
MAX_CONCURRENT_MODEL_REQUESTS = int(os.getenv("MAX_CONCURRENT_MODEL_REQUESTS", "2"))
MAX_VIDEO_SIZE_MB = int(os.getenv("MAX_VIDEO_SIZE_MB", "200"))
CONFIGURE_R2_LIFECYCLE = os.getenv("CONFIGURE_R2_LIFECYCLE", "false").lower() == "true"
OPENROUTER_MANAGEMENT_KEY = os.getenv("OPENROUTER_MANAGEMENT_KEY")
STORAGE_ACCESS_KEY = os.getenv("STORAGE_ACCESS_KEY")
STORAGE_SECRET_KEY = os.getenv("STORAGE_SECRET_KEY")
STORAGE_ENDPOINT = os.getenv("STORAGE_ENDPOINT")
STORAGE_REGION = os.getenv("STORAGE_REGION")
STORAGE_BUCKET = os.getenv("STORAGE_BUCKET")
CLOUDFLARE_ACCOUNT_ID = os.getenv("CLOUDFLARE_ACCOUNT_ID")
CLOUDFLARE_ANALYTICS_TOKEN = os.getenv("CLOUDFLARE_ANALYTICS_TOKEN")
GOOGLE_CLOUD_PROJECT = os.getenv("GOOGLE_CLOUD_PROJECT")
GOOGLE_CLOUD_ACCESS_TOKEN = os.getenv("GOOGLE_CLOUD_ACCESS_TOKEN")
PROVIDER_USAGE_CACHE_SECONDS = int(os.getenv("PROVIDER_USAGE_CACHE_SECONDS", "60"))
GITHUB_OUTPUT_ENABLED = os.getenv("GITHUB_OUTPUT_ENABLED", "false").lower() == "true"
GITHUB_OUTPUT_REPOSITORY = os.getenv(
	"GITHUB_OUTPUT_REPOSITORY", "noeltehjianhaur/AI-Media2Doc-Output"
)
GITHUB_OUTPUT_BRANCH = os.getenv("GITHUB_OUTPUT_BRANCH", "main")
GITHUB_OUTPUT_TOKEN = os.getenv("GITHUB_OUTPUT_TOKEN")
WEB_ACCESS_PASSWORD = os.getenv("WEB_ACCESS_PASSWORD", None)
